app:
    resource: "@AcmeUserBundle/Controller/"
    type:     annotation
homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'default/homepage.html.twig'
user_bundle:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
#apl_user_register:
#    resource: "@ApplicationSonataUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

# sonata front controller
#sonata_customer:
#    resource: @SonataCustomerBundle/Resources/config/routing/customer.xml
#    prefix: /shop/user

#sonata_basket:
#    resource: @SonataBasketBundle/Resources/config/routing/basket.xml
#    prefix: /shop/basket

#sonata_order:
#    resource: @SonataOrderBundle/Resources/config/routing/order.xml
#    prefix: /shop/user/invoice

#sonata_product_catalog:
#    resource: @SonataProductBundle/Resources/config/routing/catalog.xml
#    prefix: /shop/catalog

#sonata_product:
#    resource: @SonataProductBundle/Resources/config/routing/product.xml
#    prefix: /shop/product

#sonata_payment:
#    resource: @SonataPaymentBundle/Resources/config/routing/payment.xml
#    prefix: /shop/payment

#sonata_invoice:
#    resource: @SonataInvoiceBundle/Resources/config/routing/invoice.xml
#    prefix: /shop/user/invoice
