parameters:
    app.notifications.email_sender: anonymous@example.com

services:
    # first we define some basic services to make these utilities available in
    # the entire application
    slugger:
        class: Acme\UserBundle\Utils\Slugger

    markdown:
        class: Acme\UserBundle\Utils\Markdown

    # this is the Twig extension that creates the 'md2html' filter to transform
    # Markdown contents into HTML contents
    app.twig.app_extension:
        class:     Acme\UserBundle\Twig\UserExtension
        arguments: ["@markdown"]
        tags:
            - { name: twig.extension }

    app.twig.source_code_extension:
        class:     Acme\UserBundle\Twig\SourceCodeExtension
        arguments: ["@twig.loader"]
        tags:
            - { name: twig.extension }

    app.controller_listener:
        class:     Acme\UserBundle\EventListener\ControllerListener
        arguments: ["@app.twig.source_code_extension"]
        tags:
            - { name: 'kernel.event_listener', event: kernel.controller, method: registerCurrentController }

    # Uncomment the following lines to define a service for the Post Doctrine repository.
    # It's not mandatory to create these services, but if you use repositories a lot,
    # these services simplify your code:
    #
    # post_repository:
    #     class:     Doctrine\ORM\EntityRepository
    #     factory:   ["@doctrine.orm.entity_manager", getRepository]
    #     arguments: [Acme\UserBundle\Entity\Post]
    #
    # // traditional code inside a controller
    # $em = $this->getDoctrine()->getManager();
    # $posts = $em->getRepository('Acme\UserBundle:Post')->findAll();
    #
    # // same code using repository services
    # $posts = $this->get('post_repository')->findAll();
#    webservice_user_provider:
#        class: Acme\WebserviceUserBundle\Security\User\WebserviceUserProvider
#    oc_platform.beta.html:
#        class: Acme\UserBundle\Score\BetaHTML
#    oc_platform.beta.listener:
#        class: Acme\UserBundle\Score\BetaListener
#        arguments: [@oc_platform.beta.html, "2015-08-12"]
#        tags:
#            - {name:kernel.event_listener, event: kernel.response, method: processBeta }
            #- {name:kernel.event_listener, event: kernel.response, method: ignoreBeta }    
#    acme_user.score.answser:
#        class: Acme\UserBundle\Score\Score
#    acme_user.score.listener:
#        class: Acme\UserBundle\Score\ScoreListener
#        arguments: [@acme_user.score.answer, "2015-09-12"]
#        tags:
#            - {name:kernel.event_listener, event: kernel.response, method: processScore }
#            - {name:kernel.event_listener, event: kernel.response, method: ignoreScore }