<?php

namespace Proxies\__CG__\Acme\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Answer extends \Acme\UserBundle\Entity\Answer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'id', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'qcm', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'grp', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'content', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'authorEmail', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'publishedAt', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer1', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer2', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer3', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer4', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer5', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer6', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer7', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer8', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer9', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer10', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'score');
        }

        return array('__isInitialized__', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'id', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'qcm', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'grp', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'content', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'authorEmail', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'publishedAt', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer1', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer2', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer3', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer4', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer5', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer6', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer7', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer8', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer9', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'answer10', '' . "\0" . 'Acme\\UserBundle\\Entity\\Answer' . "\0" . 'score');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if (! $this->__isInitialized__) {
            $this->__initializer__ = function (Answer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if (! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function isLegitAnswer()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLegitAnswer', array());

        return parent::isLegitAnswer();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getContent()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContent', array());

        return parent::getContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setContent($content)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContent', array($content));

        return parent::setContent($content);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorEmail()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorEmail', array());

        return parent::getAuthorEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthorEmail($authorEmail)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthorEmail', array($authorEmail));

        return parent::setAuthorEmail($authorEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishedAt()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishedAt', array());

        return parent::getPublishedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishedAt($publishedAt)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishedAt', array($publishedAt));

        return parent::setPublishedAt($publishedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getQcm()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQcm', array());

        return parent::getQcm();
    }

    /**
     * {@inheritDoc}
     */
    public function setQcm(\Acme\UserBundle\Entity\Qcm $qcm = null)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQcm', array($qcm));

        return parent::setQcm($qcm);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrp()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrp', array());

        return parent::getGrp();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrp(\Acme\UserBundle\Entity\Grp $grp)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrp', array($grp));

        return parent::setGrp($grp);
    }

    /**
     * {@inheritDoc}
     */
    public function getScore()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScore', array());

        return parent::getScore();
    }

    /**
     * {@inheritDoc}
     */
    public function setScore($score)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScore', array($score));

        return parent::setScore($score);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswer1()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswer1', array());

        return parent::getAnswer1();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswer1($answer1)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswer1', array($answer1));

        return parent::setAnswer1($answer1);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswer2()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswer2', array());

        return parent::getAnswer2();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswer2($answer2)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswer2', array($answer2));

        return parent::setAnswer2($answer2);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswer3()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswer3', array());

        return parent::getAnswer3();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswer3($answer3)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswer3', array($answer3));

        return parent::setAnswer3($answer3);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswer4()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswer4', array());

        return parent::getAnswer4();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswer4($answer4)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswer4', array($answer4));

        return parent::setAnswer4($answer4);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswer5()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswer5', array());

        return parent::getAnswer5();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswer5($answer5)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswer5', array($answer5));

        return parent::setAnswer5($answer5);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswer6()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswer6', array());

        return parent::getAnswer6();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswer6($answer6)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswer6', array($answer6));

        return parent::setAnswer6($answer6);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswer7()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswer7', array());

        return parent::getAnswer7();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswer7($answer7)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswer7', array($answer7));

        return parent::setAnswer7($answer7);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswer8()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswer8', array());

        return parent::getAnswer8();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswer8($answer8)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswer8', array($answer8));

        return parent::setAnswer8($answer8);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswer9()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswer9', array());

        return parent::getAnswer9();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswer9($answer9)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswer9', array($answer9));

        return parent::setAnswer9($answer9);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswer10()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswer10', array());

        return parent::getAnswer10();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnswer10($answer10)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnswer10', array($answer10));

        return parent::setAnswer10($answer10);
    }
}
